// *** USER ***
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

// *** SETTINGS ***
export const USER_SETTINGS_UPDATE_LANGUAGE = 'USER_SETTINGS_UPDATE_LANGUAGE'
export const USER_SETTINGS_DARK_MODE_ON = 'USER_SETTINGS_DARK_MODE_ON'
export const USER_SETTINGS_DARK_MODE_OFF = 'USER_SETTINGS_DARK_MODE_OFF'
